### ISSUE TITLE
Piloter Checklist

### ISSUE THREAD

**Issue by brittweinstein** [openstax/k12#13]
- [ ] Secure piloter
- [ ] Prepare Google Docs for piloter to comment in and share
- [ ] Order materials via Amazon Wishlist
- [ ] Decide on how delivery will happen (sent to piloter or Andrew) 
- [ ] Decide on feedback return date
